## Sid Meier's Civilization 4
## Copyright 2007 BUG Mod

#BUGFfH: Modified by Denev 2009/10/05
#PEDIA_MAIN		= 200
#PEDIA_TECHS		= 201
#PEDIA_UNITS		= 202
#PEDIA_UNIT_UPGRADES	= 203
#PEDIA_UNIT_CATEGORIES	= 204
#PEDIA_PROMOTIONS	= 205
#PEDIA_PROMOTION_TREE	= 206
#PEDIA_BUILDINGS		= 207
#PEDIA_NATIONAL_WONDERS	= 208
#PEDIA_GREAT_WONDERS	= 209
#PEDIA_PROJECTS		= 210
#PEDIA_SPECIALISTS	= 211
#PEDIA_TERRAINS		= 212
#PEDIA_FEATURES		= 213
#PEDIA_BONUSES		= 214
#PEDIA_IMPROVEMENTS	= 215
#PEDIA_CIVS			= 216
#PEDIA_LEADERS		= 217
#PEDIA_TRAITS		= 218
#PEDIA_CIVICS		= 219
#PEDIA_RELIGIONS		= 220
#PEDIA_CORPORATIONS	= 221
#PEDIA_CONCEPTS		= 222
#PEDIA_BTS_CONCEPTS	= 223
#PEDIA_HINTS			= 224
#PEDIA_SHORTCUTS	= 225
#PEDIA_STRATEGY		= 226
PEDIA_MAIN,\
PEDIA_TECHS,\
PEDIA_SPELLRESEARCH,\
PEDIA_UNITS,\
PEDIA_SUMMONS,\
PEDIA_HEROES,\
PEDIA_UNIT_CATEGORIES,\
PEDIA_PROMOTIONS,\
PEDIA_PROMOTIONS_CLASS,\
PEDIA_PROMOTIONS_DISCIPLINE,\
PEDIA_PROMOTIONS_HEROIC,\
PEDIA_PROMOTION_TREE,\
PEDIA_EFFECTS,\
PEDIA_EQUIPMENTS,\
PEDIA_GEAR,\
PEDIA_RACES,\
PEDIA_SPELLS,\
PEDIA_ABILITIES,\
PEDIA_BUILDINGS,\
PEDIA_DISTRICTS,\
PEDIA_PALACES,\
PEDIA_NATIONAL_WONDERS,\
PEDIA_GREAT_WONDERS,\
PEDIA_CITY_ENCHANTMENTS,\
PEDIA_PROJECTS,\
PEDIA_PROJECTTERRAFORMS,\
PEDIA_PROJECTGLOBALS,\
PEDIA_SUMMONRITUALS,\
PEDIA_SPECIALISTS,\
PEDIA_TERRAINS,\
PEDIA_FEATURES,\
PEDIA_UNIQUE_FEATURES,\
PEDIA_BONUSES,\
PEDIA_MANA_NODES,\
PEDIA_IMPROVEMENTS_PRIMARY,\
PEDIA_IMPROVEMENTS,\
PEDIA_CIVS,\
PEDIA_LEADERS,\
PEDIA_TRAITS,\
PEDIA_CIVICS,\
PEDIA_RELIGIONS,\
PEDIA_WILDMANA_CONCEPTS,\
PEDIA_HINTS,\
PEDIA_SHORTCUTS,\
PEDIA_BTS_CONCEPTS,\
PEDIA_CONCEPTS,\
PEDIA_WILDMANA_GUIDES,\
PEDIA_STRATEGY = range(200, 248)
#BUGFfH: End Modify

##--------	BUGFfH: Added by Denev 2009/10/08
TYPE_REGULAR,\
TYPE_TEAM,\
TYPE_WORLD,\
TYPE_DISTRICT,\
TYPE_PALACE,\
TYPE_NATIONAL,\
TYPE_CITYENCHANTMENT = range(7)

TYPE_REGULAR,\
TYPE_CLASS,\
TYPE_DISCIPLINE,\
TYPE_HEROIC,\
TYPE_EFFECT,\
TYPE_EQUIPMENT,\
TYPE_GEAR,\
TYPE_RACE = range(8)

TYPE_REGULAR,\
TYPE_TEAM,\
TYPE_WORLD,\
TYPE_PROJECTTERRAFORM,\
TYPE_PROJECTGLOBAL,\
TYPE_SUMMONRITUAL = range(6)

TYPE_REGULAR,\
TYPE_SUMMON,\
TYPE_WORLDUNIT = range(3)

TYPE_REGULAR,\
TYPE_SPELLRESEARCH = range(2)

TYPE_REGULAR,\
TYPE_BONUS_MANA = range(2)

TYPE_REGULAR,\
TYPE_PRIMARY,\
TYPE_UNIQUE_FEATURES = range(3)
##--------	BUGFfH: End Add
