SOURCES= \
 "AI_Bonus.cpp" \
 "AI_ChooseProduction.cpp" \
 "AI_ChooseSpecialist.cpp" \
 "AI_ChooseTech.cpp" \
 "AI_Group.cpp" \
 "AI_GroupCityInvasion.cpp" \
 "AI_GroupSettle.cpp" \
 "AI_Hero.cpp" \
 "AI_Units.cpp" \
 "AI_War.cpp" \
 "CvArea.cpp" \
 "CvArtFileMgr.cpp" \
 "CvBarbarians.cpp" \
 "CvCity.cpp" \
 "CvCityAI.cpp" \
 "CvCombatAura.cpp" \
 "CvDeal.cpp" \
 "CvDiploParameters.cpp" \
 "CvDLLButtonPopup.cpp" \
 "CvDLLEntity.cpp" \
 "CvDLLPython.cpp" \
 "CvDllPythonEvents.cpp" \
 "CvDllTranslator.cpp" \
 "CvDLLWidgetData.cpp" \
 "CvDungeon.cpp" \
 "CvEventReporter.cpp" \
 "CvFractal.cpp" \
 "CvGame.cpp" \
 "CvGameAI.cpp" \
 "CvGameCoreDLL.cpp" \
 "CvGameCoreUtils.cpp" \
 "CvGameInterface.cpp" \
 "CvGameTextMgr.cpp" \
 "CvGlobals.cpp" \
 "CvHallOfFameInfo.cpp" \
 "CvImprovementSystem.cpp" \
 "CvInfos.cpp" \
 "CvInfoWater.cpp" \
 "CvInitCore.cpp" \
 "CvMap.cpp" \
 "CvMapGenerator.cpp" \
 "CvMessageControl.cpp" \
 "CvMessageData.cpp" \
 "CvPlayer.cpp" \
 "CvPlayerAI.cpp" \
 "CvPlot.cpp" \
 "CvPlotGroup.cpp" \
 "CvPopupInfo.cpp" \
 "CvPopupReturn.cpp" \
 "CvRandom.cpp" \
 "CvReplayInfo.cpp" \
 "CvReplayMessage.cpp" \
 "CvSelectionGroup.cpp" \
 "CvSelectionGroupAI.cpp" \
 "CvStatistics.cpp" \
 "CvStructs.cpp" \
 "CvTalkingHeadMessage.cpp" \
 "CvTeam.cpp" \
 "CvTeamAI.cpp" \
 "CvTextScreens.cpp" \
 "CvUnit.cpp" \
 "CvUnitAI.cpp" \
 "CvViewport.cpp" \
 "CvWinamp.cpp" \
 "CvXMLLoadUtility.cpp" \
 "CvXMLLoadUtilityGet.cpp" \
 "CvXMLLoadUtilityInit.cpp" \
 "CvXMLLoadUtilityModTools.cpp" \
 "CvXMLLoadUtilitySet.cpp" \
 "CvXMLLoadUtilitySetMod.cpp" \
 "CyArea.cpp" \
 "CyAreaInterface.cpp" \
 "CyArgsList.cpp" \
 "CyArtFileMgr.cpp" \
 "CyArtFileMgrInterface.cpp" \
 "CyCity.cpp" \
 "CyCityInterface1.cpp" \
 "CyCityInterface2.cpp" \
 "CyCombatAura.cpp" \
 "CyCombatAuraInterface.cpp" \
 "CyDeal.cpp" \
 "CyEnumsInterface.cpp" \
 "CyGame.cpp" \
 "CyGameCoreUtils.cpp" \
 "CyGameCoreUtilsInterface.cpp" \
 "CyGameInterface.cpp" \
 "CyGameTextMgr.cpp" \
 "CyGameTextMgrInterface.cpp" \
 "CyGlobalContext.cpp" \
 "CyGlobalContextInterface1.cpp" \
 "CyGlobalContextInterface2.cpp" \
 "CyGlobalContextInterface3.cpp" \
 "CyGlobalContextInterface4.cpp" \
 "CyHallOfFameInfo.cpp" \
 "CyHallOfFameInterface.cpp" \
 "CyInfoInterface1.cpp" \
 "CyInfoInterface2.cpp" \
 "CyInfoInterface3.cpp" \
 "CyInfoInterface4.cpp" \
 "CyMap.cpp" \
 "CyMapGenerator.cpp" \
 "CyMapGeneratorInterface.cpp" \
 "CyMapInterface.cpp" \
 "CyMessageControl.cpp" \
 "CyMessageControl2.cpp" \
 "CyMessageControlInterface.cpp" \
 "CyPlayer.cpp" \
 "CyPlayerInterface1.cpp" \
 "CyPlayerInterface2.cpp" \
 "CyPlot.cpp" \
 "CyPlotInterface1.cpp" \
 "CyRandomInterface.cpp" \
 "CyReplayInfo.cpp" \
 "CySelectionGroup.cpp" \
 "CySelectionGroupInterface.cpp" \
 "CySelectionGroupInterface2.cpp" \
 "CyStructsInterface1.cpp" \
 "CyTeam.cpp" \
 "CyTeamInterface.cpp" \
 "CyUnit.cpp" \
 "CyUnitInterface1.cpp" \
 "CyWinamp.cpp" \
 "CyWinampInterface.cpp" \
 "FAssert.cpp" \
 "FDialogTemplate.cpp" \
 "Hilfsfunktionen.cpp" \
 "Pathfinding.cpp" \
 "ThreadObject.cpp" \
 "ThreadOrganizer.cpp" \
 "TimeMeasure.cpp" \
 "Tree.cpp" \
 "_precompile.cpp" \

Debug_OBJS= \

Release_OBJS= \

